version: "3"
services:
  db:
    image: postgres
    container_name: "DB"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=SchoolDB
    ports:
      - "5432:5432"
    volumes:
      - /c/Users/gjsivevs/SchoolWebApp/postgres-data:/var/lib/postgresql/data
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "app"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/SchoolDB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
    ports:
      - "80:8080"