kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: database-master-pvc
  namespace: school-app
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi